export const board: any = {
    id: 'w-1',
    identifier: 'bag-1',
    name: 'Bag',
    backgroundType: 'transparent',
    externals: {
        x1: {
            id: 'x1',
            boardId: 'ville',
            identifier: 'external-1',
            url: '/bag.glb',
        },
    },
    cameras: {
        c1: {
            id: 'c1',
            boardId: 'ville',
            identifier: 'arc-camera-1',
            type: 'arc',
            values: {
                radius: 7,
                alpha: 0,
                beta: 1.5,
                target: [0, 0, 0],
                lowerRadiusLimit: 0,
                upperRadiusLimit: 90,
                lowerBetaLimit: 0,
                upperBetaLimit: 90,
            },
        },
    },
    lights: {},
    microAnimations: {},
    grounds: {},
    packs: {},
    particles: {},
    sounds: {},
    sprites: {},
    videos: {},
    backgroundValues: {},
};
